server:
  port: 8080
  servlet:
    encoding:
      force-response: true
  tomcat:
    uri-encoding: UTF-8
spring:
  jpa:
    hibernate:
      ddl-auto: create
#      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:8080/
    username: root
    password: password
  logging:
    level:
      root:
        DEBUG
  profiles:
    include:
      - oauth
      - jwt

springdoc:
  packages-to-scan: com.djs.dongjibsabackend.controller
  default-consumes-media-type: application/json;charset=UTF-8 # 기본 요청 타입
  default-produces-media-type: application/json;charset=UTF-8 # 기본 응답 타입

  swagger-ui:
    disable-swagger-default-url: true # 기본 경로 해제
    path: /swagger-ui.html # 기본 경로로 설정
    groups-order: desc
    operations-sorter: method
    display-request-duration: true # 요청 시간 표시

# AWS S3 환경설정 추가하기
cloud:
  aws:
    credentials:
      access-key: S3_ACCESS_KEY
      secret-key: S3_SECRET_KEY
    s3:
      bucket: S3_BUCKET_NAME
    region:
      static: S3_REGION
    stack:
      auto: false